apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test: animecoffee-web
  name: animecoffee-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      test: animecoffee-web
  template:
    metadata:
      labels:
        test: animecoffee-web
    spec:
      containers:
      - name: animecoffee-web
        env:
          - name: DATABASE_URL
            value: "mongodb+srv://yang:7ujm,.lo9@clusteryang.ishmzy9.mongodb.net/movie-app"  
        image: docker.io/yang198/yang-movie-app:develop
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: animecoffee-web
spec:
  selector:
    test: animecoffee-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30098
  type: NodePort
